# Site settings
title: WSync Pro
description: A File Import/Sync Tool
baseurl: "/WSyncPro"           # Set the subpath for GitHub Pages deployment
url: "https://wsyncpro.com/"   # Set the full URL for the site
repository: gxrwes/WSyncPro     # For github-metadata

# Use the gem version of Just the Docs so that all vendor assets (like Normalize) are provided automatically.
theme: just-the-docs

permalink: pretty

defaults:
  - scope:
      path: "docs"   # Targets all files in the "docs" folder
      type: "pages"
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Keep vendor/bundle/ for local builds
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  version: "9.1.6"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Other StillwellStudios projects":
    - "https://stillwellstudios.com"
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
nav_enabled: true
nav_sort: case_sensitive
nav_error_report: true

liquid:
  error_mode: strict
  strict_filters: true

# Footer content
back_to_top: true
back_to_top_text: "Back to top"
footer_content: >
  Copyright &copy; 2017-2020 Patrick Marsceill.
  Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a>
  <a href="https://www.netlify.com/">This site is powered by Netlify.</a>
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "View On Github"
gh_edit_repository: "https://github.com/gxrwes/WSyncPro"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Color scheme
color_scheme: dark

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
