source "https://rubygems.org"
gemspec

gem "jekyll-github-metadata", ">= 2.15"

gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins

gem "html-proofer", "~> 5.0", :group => :development

gem "csv"
gem "base64"
gem "faraday-retry"
gem "jekyll-sass-converter", "~> 3.0"
gem "sass-embedded" 

